- name: Docker
  hosts: srv
  become: true
  tasks:
    - name: Install my_sql
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - mysql-client
        - mysql-server
