- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Start NGINX service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
- name: Create HTML file with hostname
  ansible.builtin.template:
    src: index.html.j2
    mode: '0o644'  # права на /var/www/html/index.html
    dest: /var/www/html/index.htm
